#!/usr/bin/env python3
# extract_laws.py - feed the law selftests the driver's own code.
#
# The fader/master/display/EQ laws are pure integer helpers, so the
# selftests can run them in userspace - but they used to carry copies of
# them, and a fix to the driver left its selftest passing against the old
# code.  Instead, each selftest names the definitions it tests in a marker
# comment:
#
#	 * laws: bf_fader_raw_to_db2 bf_fader_db2_to_raw
#	 */
#
# (the list runs to the end of the comment), and this script prints a header holding those definitions, taken from the
# driver sources together with every driver table, #define and helper they
# use, behind a small shim for the kernel types and helpers.  selftests.sh
# compiles each selftest with it (gcc -include).
#
# Usage: python3 extract_laws.py <selftest.c>  > header.h
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DRIVER = ["babyfacepro.h", "babyfacepro.c", "babyfacepro-ctl.c"]

SHIM = """\
/* Generated by extract_laws.py from the driver sources - do not edit. */
#include <stdint.h>
#include <stdbool.h>

typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef int8_t s8;
typedef int16_t s16;
typedef int32_t s32;
typedef int64_t s64;

#define ARRAY_SIZE(a)		(sizeof(a) / sizeof((a)[0]))
#define clamp(v, lo, hi)	({ __auto_type _v = (v); \\
				   _v < (lo) ? (lo) : _v > (hi) ? (hi) : _v; })
#define ilog2(n)		(63 - __builtin_clzll((unsigned long long)(n)))
#define div_s64(a, b)		((s64)(a) / (s32)(b))
#define div64_s64(a, b)		((s64)(a) / (s64)(b))
"""

IDENT = re.compile(r"\b[A-Za-z_]\w*\b")


def strip_comments(src):
    return re.sub(r"/\*.*?\*/|//[^\n]*", " ", src, flags=re.S)


def index(src):
    """name -> (position, text) of each top-level definition in src."""
    out = {}
    lines = src.split("\n")
    pos = 0
    offs = []
    for ln in lines:
        offs.append(pos)
        pos += len(ln) + 1
    i = 0
    while i < len(lines):
        ln = lines[i]
        m = re.match(r"#define\s+(\w+)", ln)
        if m:
            j = i
            while lines[j].endswith("\\"):
                j += 1
            out.setdefault(m.group(1), (offs[i], "\n".join(lines[i:j + 1])))
            i = j + 1
            continue
        # a column-0 line naming a function or an array, not a prototype
        m = re.match(r"(?:\}\s*)?(?:[A-Za-z_][\w\s\*]*?\s\**)?(\w+)\s*([\(\[])",
                     ln)
        if m and ln[:1] not in (" ", "\t", "#", "") and \
           not re.match(r"(if|for|while|switch|return)\b", ln):
            name = m.group(1)
            start = i
            if ln.startswith("}"):     # "} name[] = {" of an inline struct
                while start > 0 and not re.match(r"[A-Za-z_]",
                                                  lines[start - 1][:1] or " "):
                    start -= 1
                start -= 1
            j = i
            if m.group(2) == "(":
                while j < len(lines) and not lines[j].rstrip().endswith(
                        (")", "{", ";")):
                    j += 1
                if lines[j].rstrip().endswith(";"):
                    i = j + 1          # a prototype
                    continue
                while j < len(lines) and lines[j] != "}":
                    j += 1
            else:
                while j < len(lines) and not lines[j].rstrip().endswith(";"):
                    j += 1
            out.setdefault(name, (offs[start], "\n".join(lines[start:j + 1])))
            i = j + 1
            continue
        i += 1
    return out


def main():
    test = open(sys.argv[1]).read()
    m = re.search(r"\blaws:(.*?)\*/", test, re.S)
    if not m:
        sys.exit("%s: no \"laws: ...\" marker comment" % sys.argv[1])
    wanted = [w for w in m.group(1).split() if w != "*"]

    defs = {}
    for n, f in enumerate(DRIVER):
        for name, (pos, text) in index(open(os.path.join(HERE, f)).read()).items():
            defs.setdefault(name, ((n, pos), text))

    done, order = set(), []

    def visit(name, chain):
        if name in done:
            return
        if name in chain:
            sys.exit("circular definition: %s" % " -> ".join(chain + [name]))
        for dep in IDENT.findall(strip_comments(defs[name][1])):
            if dep != name and dep in defs:
                visit(dep, chain + [name])
        done.add(name)
        order.append(name)

    for name in wanted:
        if name not in defs:
            sys.exit("%s: %s is not defined in the driver" % (sys.argv[1], name))
        visit(name, [])

    print(SHIM)
    for name in order:
        print(defs[name][1] + "\n")


if __name__ == "__main__":
    main()
